# Generated by Django 5.0.2 on 2024-02-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsummary',
            name='displayed_email',
            field=models.EmailField(default='abrahamniuboqian@gmail.com', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsummary',
            name='displayed_name',
            field=models.CharField(default='Dev Navin', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsummary',
            name='displayed_phone_number',
            field=models.CharField(default=87484392, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsummary',
            name='displayed_title',
            field=models.CharField(default='Vice President', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsummary',
            name='mas_number',
            field=models.CharField(default=696969, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
