# Generated by Django 5.0.2 on 2024-02-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentsummary_displayed_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsummary',
            old_name='displayed_email',
            new_name='DisplayedEmail',
        ),
        migrations.RenameField(
            model_name='studentsummary',
            old_name='displayed_name',
            new_name='DisplayedName',
        ),
        migrations.RenameField(
            model_name='studentsummary',
            old_name='displayed_phone_number',
            new_name='DisplayedPhoneNumber',
        ),
        migrations.RenameField(
            model_name='studentsummary',
            old_name='displayed_title',
            new_name='DisplayedTitle',
        ),
        migrations.RenameField(
            model_name='studentsummary',
            old_name='mas_number',
            new_name='MAS',
        ),
    ]
