# Generated by Django 5.0.2 on 2024-02-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_displayed_email_studentsummary_displayedemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsummary',
            name='DisplayedEmail',
            field=models.EmailField(max_length=255),
        ),
    ]
