# Generated by Django 5.0.2 on 2024-02-22 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentsummary_displayedemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureplan',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='OtherBenefitsRemarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentsummary',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
