# Generated by Django 5.0.2 on 2024-03-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_course_remove_student_registrationno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PremiumPayoutAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='PremiumPayoutMode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='PremiumPayoutYear',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
