# Generated by Django 5.0.2 on 2024-03-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_product_premiumpayoutamount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Yearly',
            new_name='YearlyPaymentAmount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Monthly',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Quarterly',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SemiAnnual',
        ),
        migrations.AddField(
            model_name='product',
            name='SinglePaymenAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
