# Generated by Django 5.0.2 on 2024-03-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_futureplan_currentsumassured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PremiumPayoutEndYear',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
