# Generated by Django 5.0.2 on 2024-03-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_product_premiumpayoutendyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PaymentEndDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
