# Generated by Django 5.0.2 on 2024-03-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_product_paymentenddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='CriticalIllness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
