# Generated by Django 5.0.2 on 2024-04-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_product_criticalillness_alter_product_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Type',
        ),
    ]
