# Generated by Django 5.0.2 on 2024-04-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='MaturityPremiumEndDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
