# Generated by Django 5.0.2 on 2024-04-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_product_maturitypremiumenddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Endowment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='InvLinked',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Term',
        ),
        migrations.RemoveField(
            model_name='product',
            name='WholeLife',
        ),
        migrations.AddField(
            model_name='product',
            name='BasicSumAssured',
            field=models.DecimalField(decimal_places=2, default='7000', max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Type',
            field=models.CharField(default='Term', max_length=100),
            preserve_default=False,
        ),
    ]
