# Generated by Django 5.0.2 on 2024-04-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_remove_product_basicsumassured_product_basicsum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='BasicSum',
        ),
        migrations.AddField(
            model_name='product',
            name='BasicSumAssured',
            field=models.DecimalField(decimal_places=2, default=7000, max_digits=14),
            preserve_default=False,
        ),
    ]
