# Generated by Django 5.0.2 on 2024-04-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_remove_product_basicsum_product_basicsumassured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BasicSumAssured',
            field=models.CharField(max_length=100),
        ),
    ]
