# Generated by Django 5.0.2 on 2024-04-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_product_basicsumassured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BasicSumAssured',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
