# Generated by Django 5.0.2 on 2024-04-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_alter_product_basicsumassured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='BasicSumAssured',
            new_name='BasicSum',
        ),
    ]
