version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1 # for development; remove or set to 0 for production
volumes:
  static_volume:
  media_volume:

