version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1 # for development; remove or set to 0 for production
  # frontend: # Uncomment if you have a separate Dockerfile for React
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
volumes:
  static_volume:
  media_volume:

